### DISCUSSION TITLE
Does this support playing with players on PS5?

### DISCUSSION THREAD

**Discussion by cmorierroy** [itzg/docker-minecraft-bedrock-server#389] [Q&A]
Hey, I have the server up and running. A couple of things are confusing me.

First off I'm just testing on PC.

```
version: "3.8"

services:
  mc:
    image: itzg/minecraft-bedrock-server
    ports:
      - "19132:19132/udp"
    environment:
      EULA: "TRUE"
      VERSION: "LATEST"
      TZ: America/Winnipeg
      SERVER_NAME: "etc"
      ALLOW_LIST: "true"
      ALLOW_LIST_USERS: "myuser"
      OPS: "12345"
    volumes:
      - ./mc-bedrock-data:/data
```

1. The server only pops up under the friends menu as a LAN server. I can't seem to connect to the server using the "Add Server" button (under the "Servers" menu) and my public IP. I've port-forwarded 19132 with UDP and placed myself on the allow list. Does this image support connecting over public IP even if you are running the server locally? I'm trying to confirm that this works over the internet and not just my LAN.

2. I'm setting up this server to play with my brother who's on PS5. Weirdly, PS5 has no "Add Server" button in the servers menu, so from [what I'm seeing online](https://www.youtube.com/watch?v=q9vboZUxFog), he'll have to go through a 3rd party mobile app that will make the server appear in his "Friends" menu. Before he goes through the trouble, though - does this image even support that kind of cross-platform playing? I'm relatively new to Minecraft and this "cross-platform" label isn't as straightforward as you'd expect.
