### DISCUSSION TITLE
I Can` t connect to the server with Docker Desktop

### DISCUSSION THREAD

**Discussion by AkarinLiu** [itzg/docker-minecraft-bedrock-server#478] [Q&A]
## Docker Compose file
```
services:
  server:
    image: itzg/minecraft-bedrock-server
    networks:
      - host
    environment:
      EULA: "TRUE"
      TZ: "Asia/Shanghai"
      # 服务器名称
      SERVER_NAME: "Minecraft Server"
      # 服务器描述
      SERVER_DESCRIPTION: "Minecraft Server"
      # 服务器版本
      VERSION: "LATEST"
      OPS: "2535413238764975"
      # 服务器最大玩家数量
      MAX_PLAYERS: "100"
    volumes:
      - ./data:/data
networks:
  host:
```
