### ISSUE TITLE
stdin not available

### ISSUE THREAD

**Issue by atrophic** [itzg/docker-minecraft-bedrock-server#11]
I've been successfully running your image on my synology diskstation using this docker-compose.yml:
```
version: '3.7'

services:
  bedrock:
    image: itzg/minecraft-bedrock-server
    ports:
      - "19132:19132/udp"
    volumes:                                       
      - /volume1/docker/minecraft/data:/data
    environment:
      - EULA=TRUE
      - VERSION=1.12
    restart: always
```
Everything had been working until I restarted the container, which pulled the latest image. Now I get this on startup and it repeatedly restarts:
```
time="2019-09-20T16:42:57Z" level=debug msg="Using /data to match uid and gid"
time="2019-09-20T16:42:57Z" level=debug msg="Resolved UID=1026 from match path"
time="2019-09-20T16:42:57Z" level=debug msg="Resolved GID=100 from match path"
time="2019-09-20T16:42:57Z" level=debug msg="failed to read stdin" error=EOF

EULA must be set to TRUE to indicate agreement with the Minecraft End User License
See https://minecraft.net/terms
```

I don't know what version of the image I was on previously, but I've tried all of the tags you have published and none of them work. I do know I originally got my server working on July 23rd, using whatever was the latest image at that time.

The two possible sources of problems I see are that stdin is end-of-file, so sending "stop" to it doesn't work. And that the environment variables I am configuring are not taking hold (neither EULA, VERSION, nor any arbitrary ones I try to set).

Any clue what might be causing the issues?
