### ISSUE TITLE
WARN Minecraft download page failed

### ISSUE THREAD

**Issue by claine-d** [itzg/docker-minecraft-bedrock-server#111]
My various clients have all updated and now are not able to connect to a LAN based server.  Checking the startup logs I see this:

 WARN Minecraft download page failed, so using existing download of 1.14.60.5
mc     | Starting Bedrock server...

I'm not sure why it's failing back to such and old version of the server software.  I've tried stopping and restarting a few different times and with a few different docker commands.  They all end up the same way.  The pull is successful.  The system starts up just fine but none of my iOS or Win10 devices can join the game.  We all get the Outdated Server! error.

**Comment by itzg** [comment]
The best it can do is fall back to the server binary you had already downloaded; however, I'm now wondering if the script incorrectly picking up the oldest rather than newest, if multiple were present. Can you do a `docker exec $containerNameOrId ls '/data/bedrock_server*'` to see what files are there?

Meanwhile, what logs were output after the "WARN Minecraft download page failed" one? It is supposed to provide the error output.

Also, can you docker pull the latest image to make sure you have the latest startup logic running?

**Comment by claine-d** [comment]
Hi - Thanks for your prompt reply

I'm hoping this is the output that you were expecting.  

```
sudo docker exec 087968aa24f9 ls /tank/dockers/minecraft/bedrock_server*
ls: cannot access '/tank/dockers/minecraft/bedrock_server-1.14.60.5': No such file or directory
ls: cannot access '/tank/dockers/minecraft/bedrock_server-1.16.0.2': No such file or directory
ls: cannot access '/tank/dockers/minecraft/bedrock_server-1.16.1.02': No such file or directory
ls: cannot access '/tank/dockers/minecraft/bedrock_server-1.16.20.03': No such file or directory
ls: cannot access '/tank/dockers/minecraft/bedrock_server-1.16.40.02': No such file or directory
ls: cannot access '/tank/dockers/minecraft/bedrock_server_how_to.html': No such file or directory
ls: cannot access '/tank/dockers/minecraft/bedrock_server_realms.debug': No such file or directory
```
Pull Request
```
sudo docker-compose pull
Pulling bds (itzg/minecraft-bedrock-server:latest)...
latest: Pulling from itzg/minecraft-bedrock-server
Digest: sha256:b8b627fb647b7ce3257e1fcee388bdb98d16fc7164790eaa26910dc802a3adf7
Status: Image is up to date for itzg/minecraft-bedrock-server:latest
```

Start logs
```
/tank/dockers/minecraft$ sudo docker-compose up
Creating network "minecraft_default" with the default driver
Creating mc ...
Creating mc ... done
Attaching to mc
mc     | DEBU[0000] Using /data to match uid and gid
mc     | DEBU[0000] Resolved UID=1000 from match path
mc     | DEBU[0000] Resolved GID=1000 from match path
mc     | WARN Minecraft download page failed, so using existing download of 1.14.60.5
mc     | Starting Bedrock server...
mc     | NO LOG FILE! - setting up server logging...
mc     | [2020-11-28 15:31:06 INFO] Starting Server
mc     | [2020-11-28 15:31:06 INFO] Version 1.14.60.5
mc     | [2020-11-28 15:31:06 INFO] Session ID c40d4c27-6b70-445c-b26e-70993391ddfc
mc     | [2020-11-28 15:31:06 INFO] Level Name: Bedrock level
mc     | [2020-11-28 15:31:06 INFO] Game mode: 0 Survival
mc     | [2020-11-28 15:31:06 INFO] Difficulty: 2 NORMAL
mc     | [2020-11-28 15:31:07 INFO] opening worlds/Bedrock level/db
mc     | [2020-11-28 15:31:10 INFO] IPv4 supported, port: 19132
mc     | [2020-11-28 15:31:10 INFO] IPv6 not supported
mc     | [2020-11-28 15:31:10 INFO] IPv4 supported, port: 58495
mc     | [2020-11-28 15:31:10 INFO] IPv6 not supported
mc     | [2020-11-28 15:31:12 INFO] Server started.
```

Docker Compose file for reference
```
version: '3.4'

services:
  bds:
    container_name: mc
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      VERSION: "LATEST"
      GAMEMODE: survival
      DIFFICULTY: normal
      VIEW_DISTANCE: 90
      ALLOW_CHEATS: "false"
      DEFAULT_PERMISSION_LEVEL: "Operator"
      SHOWCOORDINATES: "true"
      WHITE_LIST: 
    ports:
      - 19132:19132/udp
    volumes:
      - .:/data
    stdin_open: true
    tty: true

volumes:
  bds: {}
```
