### ISSUE TITLE
issue with permissions.json - extra comma

### ISSUE THREAD

**Issue by ebaschiera** [itzg/docker-minecraft-bedrock-server#117]
Hi,
I noticed that if I set a value to OPS parameter in `docker-compose.yml`, the generated `permissions.json` file has a syntax error, so Minecraft server discards it.

For example

```
ermanno@localhost:~/docker/minecraft$ cat docker-compose.yml
version: '3.3'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: creative
      DIFFICULTY: normal
      SERVER_NAME: TestServer
      WHITE_LIST: "false"
      MAX-PLAYERS: 5
      OPS: "123456789"
      ALLOW_CHEATS: "true"
    ports:
      - 19132:19132/udp
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true

#volumes:
#  bds: {}
```

generates the following `permissions.json` file:

```
ermanno@localhost:~/docker/minecraft$ cat data/permissions.json
[
{ "permission": "operator", "xuid": "123465789" },
]
```

The problem is the trailing comma.

I noticed [this](https://github.com/itzg/docker-minecraft-bedrock-server/commit/6a8f4aa002e3c6c2861e03ac9d3358484c206c7c) and I think that something similar should be done for permissions, but I am not very good at shell scripting, so I could't come up with a working solution.

Thanks!
