### ISSUE TITLE
Volumes location on server

### ISSUE THREAD

**Issue by jacko306** [itzg/docker-minecraft-bedrock-server#125]
I want to specify a location outside of the docked folder for the system.properties and whitelist.json I have done this in the past with previous versions of Minecraft is it possible with this one?  i have tried the -v option when setting it up but with no luck
Thanks

**Comment by itzg** [comment]
What `docker run` command line or compose have you tried? 

So far this compose file has worked for me:
```yaml
version: "3"

services:
  bedrock:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
    volumes:
      - bedrock:/data
      - ./whitelist.json:/data/whitelist.json

volumes:
  bedrock: {}
```

with this `whitelist.json` next to it
```json
[
  {
    "name": "Itz G"
  }
]
```
