### ISSUE TITLE
Server online, Port is open, Connection from PC via LAN and WLAN working, iOS not

### ISSUE THREAD

**Issue by Scratix** [itzg/docker-minecraft-bedrock-server#136]
Thanks a lot for the fantastic work! I easily installed the server on my Synology docker using docker-compose and an individual IP:
```
#Minecraft Bedrock itzg
  minecraft_bedrock:
    container_name: minecraft_bedrock
    image: itzg/minecraft-bedrock-server:latest
    hostname: minecraft-server
    environment:
      EULA: "TRUE"
    volumes:
      - '/volume1/docker/minecraft_bedrock:/data'
    stdin_open: true
    tty: true
    restart: always
    networks:
      VLAN:
        ipv4_address: 192.168.2.252
```
The server starts, is pingable, the port 19132 is open. I can easily connect via Windows 10 PE Edition. The server is listed under LAN Games. and I can add the server under the server tab and it is shown as online. When opening minecraft on iOS app the server is neither shown under LAN Games nor am I able to connect to it via the server tab. I am in the correct wifi network.

The minecraft server is broadcasting as well ( tcpdump -v udp port 19132). No errors show up in the server log. The server is running on the latest version Version 1.16.201.3 the iOS client runs on v1.16.201 (shows nothing more). 

I even tried to run it not on macvlan but on the host or bridge network. Nothing changed. PC minecraft PE is able to connect, iPad not.

Any ideas why is that?
