### ISSUE TITLE
Provide mechanism similar to rcon-cli

### ISSUE THREAD

**Issue by esticle** [itzg/docker-minecraft-bedrock-server#15]
Noob question - 
Is it possible to have rcon-cli in the container like on the java edition?

**Comment by itzg** [comment]
Actually that's a great question...but unfortunately they haven't implemented rcon in the bedrock edition so including the cli wouldn't help.

Over here https://github.com/itzg/docker-minecraft-bedrock-server/issues/8#issuecomment-528544941 I show a work around where you can `docker attach` to the bedrock container and issue commands.

**Comment by esticle** [comment]
I guessed that was the case with rcon-cli thanks @itzg 

Appreciate the pointer - just a quick one for yourself (or Nitrosito really) - what would the docker-compose equivalent look like? Not having much luck with:

```
...snip...
    ports:
      - 19132:19132/udp
    restart: unless-stopped
    command: run --rm -i  -e EULA=TRUE
```
Then,

```
# docker attach minecraft-bedrock
[2019-11-11 22:07:22 INFO] Server started.
/help
^P/help
help
^Ztime="2019-11-11T22:07:32Z" level=debug msg="Forwarding signal" signal=stopped
```

**Comment by itzg** [comment]
Here is a compose file that allows for using `docker attach` where it's the last two lines that are relevant:

```yml
version: '3.3'

services:
  bedrock:
    image: itzg/minecraft-bedrock-server
    environment: 
      EULA: "TRUE"
    ports:
      - 19132:19132/udp
    stdin_open: true
    tty: true
```

BTW, the `command` field is tempting, but it's typically for specifying the command arguments to run within the container.
