### ISSUE TITLE
include manymine.enabled=true label

### ISSUE THREAD

**Issue by chrisepp** [itzg/docker-minecraft-bedrock-server#157]
Would you consider adding the manymine.enabled=true to your docker image? For those running on Synology docker containers it would greatly simplify creating servers that support the manymine container.

**Comment by itzg** [comment]
Does it need to be a label on the image? If so, can you point me to documentation why that is?

**Comment by itzg** [comment]
...you add that label to your container:

> Add the label 'manymine.enable=true' to each server container you want manymine to announce to clients.

from https://github.com/illiteratealliterator/manymine#manymine

such as
```
  minecraft-a:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-a
    environment:
      - EULA=TRUE
      - SERVER_NAME=Server A
      - SERVER_PORT=60601
    volumes:
      - minecraft-a-data:/data
    ports:
      - '60601:60601/udp'
    labels:
      - manymine.enable=true
```
