### ISSUE TITLE
Server never starts when using Docker + Volumes

### ISSUE THREAD

**Issue by svanvliet** [itzg/docker-minecraft-bedrock-server#171]
Trying to get a persistent volume attached so that I can use this image for hosting. When attaching to a local volume (and also a volume in Azure), it hangs on the "Downloading Bedrock server version 1.17.10.04 ..." step and never progresses.

Output from console (Azure Container Instance):
```shell
time="2021-08-04T19:05:30Z" level=debug msg="Using /data to match uid and gid"
time="2021-08-04T19:05:30Z" level=debug msg="Resolved UID=0 from match path"
time="2021-08-04T19:05:30Z" level=debug msg="Resolved GID=0 from match path"
Looking up latest version...
time="2021-08-04T19:05:30Z" level=debug msg="stdin is detached, so forwarding is disabled"
Downloading Bedrock server version 1.17.10.04 ...
```

Here's my docker-compose.yaml file:
```yaml
version: "3.4"

services:
    bedrock-server:
        image: itzg/minecraft-bedrock-server
        volumes:
            - mcdata:/data
        environment: 
            EULA: "TRUE"
            GAMEMODE: survival
            DIFFICULTY: normal
        domainname: "bedrock"
        ports: 
            - "80:80"
            - "19132:19132/udp"
        stdin_open: true
        tty: true
        sysctls:
            net.ipv4.ip_local_port_range: 39132 39133
        deploy:
            resources:
                    reservations:
                        cpus: "2"
                        memory: 4G

volumes:
    mcdata:
        driver: azure_file
        driver_opts:
            share_name: mcdata
            storage_account_name: azurestorageaccount 
```

When I remove the custom volume from this compose file, it all works as expected (in Azure and on local Docker Desktop). Thanks for the help!
