### ISSUE TITLE
permissions.json not populated when OPS is set.

### ISSUE THREAD

**Issue by ghstwhl** [itzg/docker-minecraft-bedrock-server#176]
I am using docker compose with the intent to deploy multiple MCBE instances under manymine.  I've set the OPS environment variable, but permissions.json is not getting populated.

Here is my redacted docker-compose.yml file:

```
version: "3.7"
services:
  manymine:
    image: illiteratealliterator/manymine
    container_name: manymine
    ports:
      - '19132:19132/udp'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  minecraft-a:
    image: cubeworx/mcbe-server
    container_name: minecraft-a
    environment:
      EULA: "TRUE"
      SERVER_NAME: "Tristan's World"
      SERVER_PORT: "60601"
      GAMEMODE: "creative"
      ALLOW_CHEATS: "true"
      WHITE_LIST: "false"
      OPS: "XXXXXXXXXXXXXXXX"
    volumes:
      - ./minecraft-a-data:/mcbe/data
    ports:
      - '60601:60601/udp'
    stdin_open: true
    tty: true
    labels:
      - manymine.enable=true
```

As you can see, when the instance comes up, permissions.json is an an empty list:

```
# docker-compose up
WARNING: Found orphan containers (minecraft-b, minecraft-c) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting manymine    ... done
Starting minecraft-a ... done
Attaching to manymine, minecraft-a
minecraft-a    | ###########################################
minecraft-a    | Already initialized. Did container restart?
minecraft-a    | Checking for .mcaddon, .mcpack, or .zip files in /mcbe/data/addons.
minecraft-a    | Checking /mcbe/data/addons for behavior_packs.
minecraft-a    | Creating /mcbe/data/worlds/Bedrock-Level/world_behavior_packs.json
minecraft-a    | Adding pack.name uuid & version to /mcbe/data/worlds/Bedrock-Level/world_behavior_packs.json
minecraft-a    | Checking /mcbe/data/addons for resource_packs.
minecraft-a    | Creating /mcbe/data/worlds/Bedrock-Level/world_resource_packs.json
minecraft-a    | Adding pack.name uuid & version to /mcbe/data/worlds/Bedrock-Level/world_resource_packs.json
minecraft-a    | Starting Minecraft Bedrock Server Version 1.17.11.01 with the following configuration:
minecraft-a    | ########## SERVER PROPERTIES ##########
minecraft-a    | allow-cheats=true
minecraft-a    | compression-threshold=1
minecraft-a    | content-log-file-enabled=false
minecraft-a    | correct-player-movement=false
minecraft-a    | default-player-permission-level=member
minecraft-a    | difficulty=easy
minecraft-a    | force-gamemode=false
minecraft-a    | gamemode=survival
minecraft-a    | level-name=Bedrock-Level
minecraft-a    | level-seed=
minecraft-a    | max-players=10
minecraft-a    | max-threads=8
minecraft-a    | online-mode=true
minecraft-a    | player-idle-timeout=30
minecraft-a    | player-movement-distance-threshold=0.3
minecraft-a    | player-movement-duration-threshold-in-ms=500
minecraft-a    | player-movement-score-threshold=20
minecraft-a    | server-authoritative-block-breaking=false
minecraft-a    | server-authoritative-movement=server-auth
minecraft-a    | server-name=Tristan's World
minecraft-a    | server-port=60601
minecraft-a    | server-portv6=19133
minecraft-a    | texturepack-required=false
minecraft-a    | tick-distance=4
minecraft-a    | view-distance=32
minecraft-a    | white-list=false
minecraft-a    | ###############################
minecraft-a    | 
minecraft-a    | ########## PERMISSIONS ##########
minecraft-a    | []
minecraft-a    | #################################
minecraft-a    | 
minecraft-a    | ########## WHITELIST ##########
minecraft-a    | []
minecraft-a    | #################################
manymine       | MM_LISTEN_PORT=19132
manymine       | Listening for pings at 0.0.0.0:19132
manymine       | Server added: /minecraft-a (42ff743b6ad4c6b6fe163c948f4596cf06cd46f9c05473c57592b9f0ca7dda7f)
manymine       | Server /minecraft-a is running on internal port 60601 and external port 60601
minecraft-a    | NO LOG FILE! - setting up server logging...
minecraft-a    | [2021-08-20 22:43:15 INFO] Starting Server
minecraft-a    | [2021-08-20 22:43:15 INFO] Version 1.17.11.01
minecraft-a    | [2021-08-20 22:43:15 INFO] Session ID aad5ef1b-10ce-4f36-983c-74e8956dff14
minecraft-a    | [2021-08-20 22:43:15 INFO] Level Name: Bedrock-Level
minecraft-a    | [2021-08-20 22:43:15 INFO] Game mode: 0 Survival
minecraft-a    | [2021-08-20 22:43:15 INFO] Difficulty: 1 EASY
minecraft-a    | [INFO] opening worlds/Bedrock-Level/db
manymine       | /minecraft-a (172.18.0.3:60601) changed state from [Initial] to [No Response]
minecraft-a    | [INFO] IPv4 supported, port: 60601
minecraft-a    | [INFO] IPv6 not supported
minecraft-a    | [INFO] IPv4 supported, port: 19132
minecraft-a    | [INFO] IPv6 not supported
minecraft-a    | [INFO] Server started.
manymine       | /minecraft-a (172.18.0.3:60601) changed state from [No Response] to [Connected]
```

I tried manually configuring the permissions.json and using `chattr +i permissions.json` but then the server just fails to start with an error in the shell script that constructs permissions.json

I've found that I can connect to the container and grant OP permission, and permissions.json is updated, but that doesn't persist between container restarts.
