### ISSUE TITLE
Network port occupied, can't start server.

### ISSUE THREAD

**Issue by weihao** [itzg/docker-minecraft-bedrock-server#195]
```
DEBU[0000] Using /data to match uid and gid
DEBU[0000] Resolved UID=1000 from match path
DEBU[0000] Resolved GID=1000 from match path
Looking up latest version...
Downloading Bedrock server version 1.17.41.01 ...
Starting Bedrock server...
NO LOG FILE! - [] setting up server logging...
NO LOG FILE! - [2021-11-30 17:45:31:434 INFO] Starting Server
NO LOG FILE! - [2021-11-30 17:45:31:436 INFO] Version 1.17.41.01
NO LOG FILE! - [2021-11-30 17:45:31:436 INFO] Session ID fb7c0c89-7178-485e-aba3-3553d5e55006
NO LOG FILE! - [2021-11-30 17:45:31:444 INFO] Level Name: Bedrock level
NO LOG FILE! - [2021-11-30 17:45:31:475 INFO] Game mode: 0 Survival
NO LOG FILE! - [2021-11-30 17:45:31:475 INFO] Difficulty: 3 HARD
NO LOG FILE! - [INFO] opening worlds/Bedrock level/db
NO LOG FILE! - [ERROR] DBStorage chain is invalid. Possibly encryption-related, or bad DBStorageConfig passed. Reason: Unable to decipher/decrypt LevelDB.
NO LOG FILE! - [ERROR] Network port occupied, can't start server.
```

```
server-port=19132
# Which IPv4 port the server should listen to.
# Allowed values: Integers in the range [1, 65535]

server-portv6=19133
```

**Comment by itzg** [comment]
Can you provide the compose file or docker run command used to create the container?

**Comment by weihao** [comment]
```
version: "3.8"

services:
  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: unless-stopped
    depends_on:
      - "survival"
    environment:
      BACKUP_INTERVAL: "12h"
      TZ: "America/New_York"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backups:/backups
      - ./survival:/survival
  survival:
    image: itzg/minecraft-bedrock-server
    container_name: survival
    restart: unless-stopped
    environment:
      EULA: "TRUE"
    volumes:
      - ./survival:/data
    stdin_open: true
    tty: true
```
