### ISSUE TITLE
Permission Issues - Raspberry Pi Ubuntu

### ISSUE THREAD

**Issue by ElectroMagneticInterference** [itzg/docker-minecraft-bedrock-server#205]
I am working on gettings this set up on a Raspberry Pi 4B, and I keep getting issues inside of the container saying it has a lack of permissions to run a script.
I'm pretty sure it has some issue with accessing the ./server file, but when I change this volume to have docker create the volume, it still has the same issue.

I tried running it as root, just to see if that helped, but it didn't.

I am not entirely sure what's going wrong, as it works on my desktop running windows, and it doesn't seem like an issue caused by it being on the raspberry pi.

docker-compose.yaml:
```YAML
version: '3.8'

services:
  mc-server:
    image: itzg/minecraft-bedrock-server:latest
    restart: on-failure
    stdin_open: true

    env_file:
      - ./mc-server.env

    ports:
      - "19132:19132/udp"

    volumes:
      - ./server:/data
```
command and output:
```
ubuntu@minecraft-pi:~/minecraft$ sudo docker-compose up
Starting minecraft_mc-server_1 ... done
Attaching to minecraft_mc-server_1
mc-server_1  | time="2022-01-02T21:28:02Z" level=fatal msg="Failed to run sub-command" error="fork/exec /data: permission denied"
minecraft_mc-server_1 exited with code 1
```

I don't think it would be helpful, but here is the environment file
```ENV
EULA="TRUE"
LEVEL_NAME="My World"
GAMEMODE=creative
DIFFICULTY=peaceful
ALLOW_CHEATS=true
DEFAULT_PLAYER_PERMISSION_LEVEL=operator
SERVER_NAME="My Dedicated Server"
SERVER_PORT=19132
```
