### ISSUE TITLE
Starting Bedrock server... crushing

### ISSUE THREAD

**Issue by kbartczakpl** [itzg/docker-minecraft-bedrock-server#225]
yaml:
```yaml
 bds:
    image: itzg/minecraft-bedrock-server
    container_name: mine-bds
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
    ports:
      - 19132:19132/udp
    volumes:
      - /media/docker/minecraft/bds:/data
    stdin_open: true
    tty: true
```
logs:
```
DEBU[0000] Using /data to match uid and gid
DEBU[0000] Resolved UID=0 from match path
DEBU[0000] Resolved GID=0 from match path
Looking up latest version...
Starting Bedrock server...
/opt/bedrock-entry.sh: line 163: /data/bedrock_server-1.18.12.01: Permission denied
```

any suggestions?
