### ISSUE TITLE
Update automatically

### ISSUE THREAD

**Issue by joshuaganger** [itzg/docker-minecraft-bedrock-server#233]
Would it be possible for this to update automatically?  I understand that I can restart the container and it will pull the latest bedrock server version, but I'm not sure how to know when updates are released.  Right now it feels like I have to wait until clients are unable to connect before I'll know.  This isn't ideal because I may not be immediately available when the issue arises.  Thoughts?

**Comment by nomad64** [comment]
Although not ideal, you could use Watchtower to automate updating your server containers. You would need to be careful to schedule Watchtower to run _after_ a backup runs, so you have a known-good copy if there are any issues.

**Comment by itzg** [comment]
@joshuaganger is right. Instead, something would need to watch the download page like https://github.com/itzg/docker-minecraft-bedrock-server/blob/master/bedrock-entry.sh does and notice when the referenced download URL changes.

**Comment by nomad64** [comment]
Sorry, I should explained myself better.

You can use Watchtower with its scopes and schedules to perform a daily container restart.

To accomplish this, we need to assign each bedrock server container the scope label in `docker-compose.yml`:
```
version: '3.4'
services:
  bedrock_server_1:
    image: itzg/minecraft-bedrock-server:latest
    labels:
      com.centurylinklabs.watchtower.scope: bedrock_srv
    environment:
      TZ: "America/Chicago"
```

Then (either in the same or separate `docker-compse.yml`) setup Watchtower to run on a daily schedule with the defined scope:
```
  watchtower:
    image: containrrr/watchtower
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 3 * * ?" --scope bedrock_srv
    labels:
      com.centurylinklabs.watchtower.scope: bedrock_srv
    environment:
      TZ: "America/Chicago"
```

The above example will tell Watchtower to run at 3am daily, and only execute against the containers with the defined scope label (bedrock_srv). Similar to performing backups, setting the TZ value is important.

Obviously, this method is not perfect and I still very much support an in-container method of server updates. Also, I am not sure what time of day MCBE updates are normally pushed, as that would impact the schedule. However, this _should_ at least somewhat-automate your server updates.

**Comment by nomad64** [comment]
So I wrote this whole thing about Watchtower scopes and schedules, then realized I was being silly because that doesn't solve anything. Sorry for the spam. :(

I think the "best" way to somewhat-automate updates is to just restart the containers on a schedule. Assuming you use a standardized name for your containers, this can be done by another container using the following docker-compose:
```
version: '3.7'
services:
  restart_agent:
    image: alpinelinux/docker-cli
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: docker container restart -t 30 $(docker ps --filter name=mc_bedrock_srv* --quiet)
    deploy:
      restart_policy:
        delay: 24h
```

The `name=` variable accepts regular expressions. In my case, all of my server containers are prefixed with `mc_bedrock_srv`, so it is an easy glob.

Note that this runs on a loosely-defined schedule that will shift, which is not ideal. Alternatively, just scheduling a cronjob to run `docker container restart -t 30 $(docker ps --filter name=mc_bedrock_srv* --quiet)` may work better.
