### ISSUE TITLE
Unable to start up server

### ISSUE THREAD

**Issue by DevRedempti** [itzg/docker-minecraft-bedrock-server#255]
Here is the Error

exec /usr/local/bin/entrypoint-demoter: exec format error

I found this error in the logs in portainer.

here is my docker-compose.yml

```
version: '3.4'

services:
  minecraftbedrock:
    image: itzg/minecraft-bedrock-server
    volumes:
      - minecraftbedrockdata:/data
    ports:
      - 19132:19132/udp
    environment:
      EULA: "TRUE"
      VERSION: "LATEST"
      GAMEMODE: survival
      DIFFICULTY: hard
      OPS: "aaaaa"
      ALLOW_LIST: "TRUE"
      PLAYER_IDLE_TIMEOUT: 0
      MAX_PLAYERS: 10
    stdin_open: true
    tty: true
volumes:
  minecraftbedrockdata:
    external: true
```

I'm not so good with Docker yet and this is my first time trying out making a minecraft server so I really have no idea what the error is here nor what to search for.

I've been googling things up for hours but haven't found anything, so I'm trying here.
Any help will be much appreciated. Thank you so much!
