### ISSUE TITLE
"Unable to connect" to world on iOS device but works fine on Windows 11

### ISSUE THREAD

**Issue by jweymarn** [itzg/docker-minecraft-bedrock-server#284]
Hi,
I launched a world and it works fine with _Minecraft for Windows (Bedrock edition)_ **on Windows 11**. However when I try to connect to it with my iPhone running _Minecraft PE_ I get "cannot connect to world". iPhone is on same LAN. 

**Do I need to add some config to get it to work with Minecraft PE?**

My compose file:
```
version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: creative
      DIFFICULTY: hard
      LEVEL_SEED: "2006386677"
      ALLOW_CHEATS: "true"
      #  WHITE_LIST: "true"
      DEFAULT_PLAYER_PERMISSION_LEVEL: operator
    ports:
      - 19132:19132/udp
    volumes:
      - /opt/minecraft-bedrock/creative-1:/data
    stdin_open: true
    tty: true

volumes:
  bds: {}
```

On my iPhone I also cannot see the world under "Friends" while it does show up on Windows 11 PC.
