### ISSUE TITLE
Docker-Compose send-command

### ISSUE THREAD

**Issue by johane73** [itzg/docker-minecraft-bedrock-server#297]
I'm trying to use the send-command to set gamerules, for example pvp = false

I am using docker-compose:

```
version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    container_name: "MC_123"
    privileged: true
    restart: always
    ports:
      - 11111:19132/udp
    environment:
      SERVER_NAME: "Test server"
      EULA: "TRUE"
      GAMEMODE: "survival"
      DIFFICULTY: "easy"
      VIEW_DISTANCE: "16"
      ALLOW_CHEATS: "true"
      WHITE_LIST_USERS: "me"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
```

then sending:

```
docker exec MC_123 send-command gamerule pvp
```

but I'm getting:
```
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "send-command": executable file not found in $PATH: unknown
```

Any ideas?
