### ISSUE TITLE
Error: PageSize configuration is wrong: configured with 4096, but got 65536

### ISSUE THREAD

**Issue by travisboss** [itzg/docker-minecraft-bedrock-server#348]
```
[+] Running 1/1
 ⠿ Container mc-bedrock  Started                                                                                  0.4s
DEBU[0000] Using /data to match uid and gid
DEBU[0000] Resolved UID=0 from match path
DEBU[0000] Resolved GID=0 from match path
Looking up latest version...
Starting Bedrock server...
Error: PageSize configuration is wrong: configured with 4096, but got 65536
```

```yaml
  mc-bedrock:
    image: itzg/minecraft-bedrock-server
    container_name: mc-bedrock
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
    ports:
      - 19134:19132/udp
    volumes:
      - ./minecraft-bedrock-data:/data
    stdin_open: true
    tty: true
```

Trying to figure out this error, I have changed the port for now since I am running mc-java with geyersmc on another container, checked `server.properties` but see nothing related to this issue.  I am running on a ARM oracle free tier.
