### ISSUE TITLE
Game will only start in survival

### ISSUE THREAD

**Issue by Phil-T1** [itzg/docker-minecraft-bedrock-server#374]
Hi,

This could be me as I don't know Minecraft, but the game only seems to start in survival mode, where zombies attack and I take damage.

I want creative mode  for my 4 year old kid. If  it is me then can anybody see  where I've gone wrong?

```
version: '3.4'

services:

  minecraft:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft
    restart: unless-stopped
    environment:
      TZ: Europe/London
      VERSION: LATEST
      SERVER_NAME: Minecraft World
      EULA: "TRUE"
      GAMEMODE: creative
      DIFFICULTY: easy
    ports:
        - 19132:19132/udp
    stdin_open: true
    tty: true
    volumes:
      - ./data:/data
```

Thanks in advance!

Phi.

**Comment by itzg** [comment]
I'll have to test this out myself, but I believe some of the settings like game mode are baked into the world data until a server command is used to change that. One option to try is stopping the container, deleting the world data, and letting it regenerate with the `GAMEMODE` in place.

**Comment by jump** [comment]
Hm, I'm seeing this a full 2 years later. Except I've completely nuked and deleted the data folder, forcing a clean rebuild of everything - and yet its still coming up in default "SURVIVAL" mode. 

```
services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: kids-minecraft
    pull_policy: daily
    environment:
      VERSION: "LATEST"
      PAPER_CHANNEL: "experimental"
      TYPE: "PAPER"
      EULA: "true"
      MEMORY: 10G
      GAMEMODE: "creative"
      DIFFICULTY: "easy"
      FORCE_GAMEMODE: "TRUE"
      DOWNLOAD_PLUGINS: >-
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
    ports:
      - "25565:25565"     # Java Edition Port
      - "19132:19132/udp" # Bedrock Edition Port
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
```


which is producing startup output including: 
```
kids-minecraft  | [17:34:47] [Server thread/INFO]: This server is running Paper version 1.21.11-54-main@6da8af7 (2025-12-23T19:13:29Z) (Implementing API version 1.21.11-R0.1-SNAPSHOT)
kids-minecraft  | [17:34:47] [Server thread/INFO]: This server bundles the spark profiler. For more information please visit https://docs.papermc.io/paper/profiling
kids-minecraft  | [17:34:47] [Server thread/INFO]: Server Ping Player Sample Count: 12
kids-minecraft  | [17:34:47] [Server thread/INFO]: Using 4 threads for Netty based IO
kids-minecraft  | [17:34:48] [Server thread/INFO]: Paper is using 2 worker threads, 1 I/O threads
kids-minecraft  | [17:34:48] [Server thread/INFO]: Default game type: SURVIVAL
kids-minecraft  | [17:34:48] [Server thread/INFO]: Generating keypair
kids-minecraft  | [17:34:48] [Server thread/INFO]: Starting Minecraft server on *:25565
kids-minecraft  | [17:34:48] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
kids-minecraft  | [17:34:48] [Server thread/INFO]: Paper: Using OpenSSL 3.x.x (Linux x86_64) cipher from Velocity.
kids-minecraft  | [17:34:48] [Server thread/INFO]: Preparing level "world"
kids-minecraft  | [17:34:49] [Server thread/INFO]: Selecting spawn point for world 'minecraft:overworld'...
kids-minecraft  | [17:34:55] [Server thread/INFO]: Selecting spawn point for world 'minecraft:the_nether'...
```
