### ISSUE TITLE
Major bugs but logs are empty

### ISSUE THREAD

**Issue by itsmebasti** [itzg/docker-minecraft-bedrock-server#391]
Hi there, first of all, thanks for this project!

Two days ago I decided to run my first Minecraft server. It has to be a Bedrock server and I already ordered this ARM vServer. So this project was my way to go.

Since the beginning, my friends and I experienced issues we didn't stumble over when playing the latest Bedrock on our machines locally.
The problem is that we suddenly are not fully linked to the server, but we are still playing. Things get really odd then. I can reproduce it, by running around with a horse, but it also happens just while building things or mining stuff.

Some things that happen:
The Inventory menu does not open.
I always get moved back to a specific spot after crossing a specific border (chunks?).
I am able to mine in one place, but a view blocks further blocks get removed when I just try to mine them.
Blocks start dropping through multiple books, removing them, when I place them.
The server told me a friend fell too deep and died when he was still building his house. He logged in again, the house was built but his stuff was gone, so yes, he died.

So, a lot of weird things happen.
I tried playing around with the server/player sync configs, but nothing changed at all.
It's hard to find anyone online experiencing the same, so I thought I might try it right here.
I think my vServer should be able to handle this project, but let me know if it doesn't.

My server specs:

RAM | 8,192 MiB
CPU | 6
Architecture | ARM64
Disk 1 | 256 GiB

I tried two Linux versions, both result in the same:
    Debian (12) Bookworm arm64 / Minimal
    Ubuntu 22.04 LTS arm64 / Minimal

compose.yml
```yml
services:
  dreamland:
    image: itzg/minecraft-bedrock-server
    container_name: dreamland
    environment:
      - EULA=true
      - GAMEMODE=survival
      - DIFFICULTY=peaceful
      - OPS=1231231231231231
      - WHITE_LIST_USERS=player1,player2,player3
      - SERVER_NAME=Traumland
      - LEVEL_NAME=Traumland
      - ALLOW_CHEATS=true
      - MAX_PLAYERS=5
    ports:
      - "19132:19132/udp"
    volumes:
      - dreamland:/data
    stdin_open: true
    tty: true

volumes:
  dreamland:
    external: true
    name: dreamland
```

The terminal does not output anything about these odd things and the logs are not created when I turn them on in the server settings.
I am happy for any hint, thanks in advance!
Basti
