### ISSUE TITLE
Vwersion 1.21.31.04 not downloading

### ISSUE THREAD

**Issue by rippo** [itzg/docker-minecraft-bedrock-server#464]
My docker today is now showing this when I try to start the minecraft server, can anyone help?

```
2024-10-04 17:55:17 Downloading Bedrock server version 1.21.31.04 ...
2024-10-04 17:55:17 curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
2024-10-04 17:55:17 ERROR failed to download from https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.21.31.04.zip
2024-10-04 17:55:17       Double check that the given VERSION is valid
```

My YML file

```
volumes:
  data:

name: games

services:
  wildes: 
    image: itzg/minecraft-bedrock-server:latest
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      LEVEL_SEED: 2006386677
      VERSION: "LATEST"
    volumes:
      - /D/Games/itzg.Bedrock/Worlds/wildes/:/data/worlds
    ports:
      - "19132:19132/udp"
    stdin_open: true
    tty: true
  
  game001:
    image: itzg/minecraft-bedrock-server:latest
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      LEVEL_SEED: 8798240844535338057
      VERSION: "LATEST"
    volumes:
      - /D/Games/itzg.Bedrock/Worlds/game001/:/data/worlds
    ports:
      - "19133:19132/udp"
    stdin_open: true
    tty: true

  game002:
    image: itzg/minecraft-bedrock-server:latest
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      VERSION: "LATEST"
    volumes:
      - /D/Games/itzg.Bedrock/Worlds/game002/:/data/worlds
    ports:
      - "19134:19132/udp"
    stdin_open: true
    tty: true

```
