### ISSUE TITLE
Trying to update bedrock Minecraft server in Docker on macOS and load existing volume with Minecraft world we have been working on

### ISSUE THREAD

**Issue by txchou** [itzg/docker-minecraft-bedrock-server#466]
Hi

As noted, we have a bedrock server which needed updating. I couldn't figure out to update the existing container so made a new one. But I can't seem to load old volumes - it seems to keep creating new ones. Unfortunately, as I'm a bit of a novice - it's a bit of a mess with a bunch of containers and volumes. I've tried numerous times with ChatGPT assistance but seem to be going around in circles making new containers which generate new worlds/volumes.

Before I give up and lose the kids' world that we've been working on for a while - thought I'd ask here.

docker-compose.yml looks like this:

```
services:
  minecraft:
    image: itzg/minecraft-bedrock-server:latest
    container_name: happy_blackburn
    environment:
      - EULA=TRUE
    volumes:
      - mc-bedrock-data:/data
    ports:
      - "19132:19132/udp"
volumes:
  mc-bedrock-data:
```

But it just seems to create a new volume:
```

		"Mounts": [
			{
				"Type": "volume",
				"Source": "minecraft-server_mc-bedrock-data",
				"Target": "/data",
				"VolumeOptions": {}
			}
```

If anyone can point me in the right direction, would be grateful!
