### ISSUE TITLE
Cannot discover on the latest version of Minecraft on Xbox

### ISSUE THREAD

**Issue by officialh1** [itzg/docker-minecraft-bedrock-server#499]
On the PC, you can create a map to the server and it works fine. Ever since the latest updates to Minecraft on XBox, it would periodically show and now, no longer show at all. I see the network broadcasts from XBox but server doesn't seem to do anything.

**Comment by officialh1** [comment]
![Image](https://github.com/user-attachments/assets/5b8011c0-c39b-4888-9046-79c8109e9dc0)

Note server is loading fine and firewalls are disabled on the appliance.

Host OS is 24.04

Broadcasts from XBox not being answered:

<img width="338" alt="Image" src="https://github.com/user-attachments/assets/8ca99ba4-10e2-4f42-a360-df4480c2bd70" />

**Comment by itzg** [comment]
With those traces you may want to look inside the packets (they'll be Raknet protocol) and see what IP address it is answering to the broadcast. I'm wondering if the bedrock server is advertising the container's IP address when what the Xbox will need is the host's IP address. Speaking of which, using host networking instead of default bridge network might help.

**Comment by officialh1** [comment]
To be clear, the 100.222 is the XBox and the trace is from the docker server, which is seeing the broadcasts from the XBox.

Having said that, I will have an issue if the host networking is needed as I have more than one IP assigned to allow multiple worlds on one server. I will make the changes and test with one of the worlds.

**Comment by officialh1** [comment]
The host networking did work (somewhat), but for those that co-host multiple worlds in different containers on the same host, this is a sample docker compose file (adjust accordingly):

```
services:
  minecraft-bedrock-server:
    image: itzg/minecraft-bedrock-server:latest
    container_name: mc1
    networks:
      macvlan_net:
        ipv4_address: 192.168.xxx.xxx
    environment:
      EULA: "TRUE"
      GAMEMODE: "survival"
      DIFFICULTY: "easy"
      SERVER_NAME: "Survival Server"
      ONLINE_MODE: "false"
    volumes:
      - ./data:/data
      - ./worlds:/worlds
      - ./config:/config
      - ./logs:/logs
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped

networks:
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: ens160
      macvlan_mode: bridge
    ipam:
      config:
        - subnet: 192.168.xxx.0/24
          gateway: 192.168.xxx.xxx
```

put this file in /opt/mc1
cd to /opt/mc1 and then:
docker compose up -d

This is on Ubuntu 24.04 and one would need to alter the IP information and PARENT device in the macvlan_net section. This will allow you to specify different IPs for each container. Keep in mind, the IPs cannot be consumed elsewhere (including on the docker host machine) and if you are running a VM you need to have promiscuous mode enabled on the port group otherwise network communication will not happen.

Having said all that, the network servers show for a moment. Usually on start of Minecraft or after a resume from minimize. The behavior is the same for PC and XBox versions, so this issue is not dependent on OS or device. This means my issue now goes to the coders of Minecraft, thank you.
