### ISSUE TITLE
The PS5 version cannot detect any LAN Minecraft servers; the only option is sending an invitation.

### ISSUE THREAD

**Issue by Alien-hide** [itzg/docker-minecraft-bedrock-server#504]
The PS5 version cannot detect any LAN Minecraft servers. After laset game update.

In Windows version all perfect.

**Comment by itzg** [comment]
Duplicate of #427

**Comment by boredazfcuk** [comment]
LAN discovery working fine here, on PS4 and PS5, with latest version of Minecraft.

I'm using macvlan for network type which assigns an IP address to each of the three Minecraft container I have e.g.:
```
volumes:
   minecraft1_data:
      name: minecraft1_data

networks:
   external_macvlan:
      name: external_macvlan
      driver: macvlan
      enable_ipv6: false
      ipam:
         config:
            - subnet: 10.10.10.0/24
              gateway: 10.10.10.1
      driver_opts:
         parent: eno1

services:
   minecraft1:
      user: "1010"
      container_name: minecraft1
      hostname: minecraft1
      env_file:
         - minecraft_common.env
      environment:
         - SERVER_NAME=Main
         - GAMEMODE=survival
         - DIFFICULTY=peaceful
         - DISABLE_PLAYER_INTERACTION=true
      image: itzg/minecraft-bedrock-server:latest
      networks:
         external_macvlan:
            ipv4_address: 10.10.10.10
            aliases:
             - minecraft1
      mac_address: 00-00-10-10-10-10
      volumes:
         - minecraft1_data:/data
      restart: always
      stdin_open: true
      tty: true
```

I found that two of the servers would not appear if I used my standard bridge based network driver like this:
```
networks:
   containers:
      name: containers
      driver: bridge
      enable_ipv6: false
      ipam:
         driver: default
         config:
            - subnet: 10.10.10.0/24

services:
   minecraft1:
      user: "1010"
      container_name: minecraft1
      hostname: minecraft1
      env_file:
         - minecraft_common.env
      environment:
         - SERVER_NAME=Main
         - GAMEMODE=survival
         - DIFFICULTY=peaceful
         - DISABLE_PLAYER_INTERACTION=true
      image: itzg/minecraft-bedrock-server:latest
      networks:
         containers:
            aliases:
               - minecraft1
      mac_address: 00-00-10-10-10-10
      volumes:
         - minecraft1_data:/data
      restart: always
      stdin_open: true
      tty: true
```

Maybe it's struggling when using bridge based networks?
