### ISSUE TITLE
Multiple LAN Game instances on a single Docker host with multiple IPs.

### ISSUE THREAD

**Issue by claflico** [itzg/docker-minecraft-bedrock-server#52]
I'm trying to figure out how to run multiple instances on a single docker server with multiple IPs. I don't want my kids to have to login so I would like them to show up under LAN Games.

Issue 1 is that if I launch a container and specify an IP address for the server port it doesn't show up under LAN games. 
SHOWS UP: `-p 19132:19132/udp`
DOESN'T SHOW UP:  `-p 192.168.200.212:19132:19132/udp`

When I do "tcpdump" like you've referenced in other replies I do see traffic being received on that IP from my phone even when the server doesn't show up under LAN Games.

Issue 2 is that if I change the server port to say 19135 it doesn't show up under LAN Games either.

I'm also experimenting with "phantom" to see if I can get it to act as a proxy as well but not having much luck with it yet either. https://github.com/jhead/phantom

Thanks

**Comment by itzg** [comment]
This sounds similar to this issue https://github.com/itzg/docker-minecraft-bedrock-server/issues/28, but that might have been of the places you saw `tcpdump` mentioned.

As for port 19135, I'm guessing that doesn't up in LAN games since the client is only sending broadcast packets out to port 19132.

**Comment by claflico** [comment]
Thanks for the reply. Apologies for the duplicate issue. I had looked through the titles and searched but must have been using poorly chosen keywords.

I think that I have it working using the macvlan.....Portainer kept throwing errors on the docker-compose.yml file but when I went to command line I got the below to launch the services.


```
version: '2.4'
volumes:
  creative-data:
    driver: local
  survival-data:
    driver: local
services:
  creative:
    image: itzg/minecraft-bedrock-server
    environment:
      DIFFICULTY: easy
      EULA: 'TRUE'
      GAMEMODE: creative
      LEVEL_NAME: Creative
      ONLINE_MODE: 'false'
      SERVER_NAME: Creative
      VERSION: 1.14
    volumes:
    - creative-data:/data
    ports:
    - 19132:19132/udp
    hostname: minecraft-creative
    networks:
      lan_network:
        ipv4_address: 192.X.X.216
    stdin_open: true
    tty: true
  survival:
    image: itzg/minecraft-bedrock-server
    environment:
      DIFFICULTY: easy
      EULA: 'TRUE'
      GAMEMODE: survival
      LEVEL_NAME: Survival
      ONLINE_MODE: 'false'
      SERVER_NAME: Survival
      VERSION: 1.14
    volumes:
    - survival-data:/data
    ports:
    - 19132:19132/udp
    hostname: minecraft-survival
    networks:
      lan_network:
        ipv4_address: 192.X.X.217
    stdin_open: true
    tty: true
networks:
  lan_network:
    driver: macvlan
    driver_opts:
      parent: enp2s0
    ipam:
     config:
       - subnet: 192.X.X.0/24
         gateway: 192.X.X.254
```
