### ISSUE TITLE
Another Noob Question

### ISSUE THREAD

**Issue by tofferr** [itzg/docker-minecraft-bedrock-server#58]
Complete Docker noob, and not so good at Minecraft.  I did get the docker running on my MacOS desktop.  The kids and I are connecting from our iOS devices (though it seems to be a bit unreliable on making the connection), but, none of us are operator.  I cannot figure out how to find the server.properties file to edit it, or a command line where I can issue Minecraft commands.  Any help would be much appreciated.  Thank you.

**Comment by IvanTurgenev** [comment]
damn os x docker is slow, especially io. as for the rest.

use docker-compose makes life easier create a file inside a folder called bds, name the file docker-compose.yml
put this inside
```
version: '3.4'
services:
  bds:
    container_name: bds
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: hard
    ports:
      - 19132:19132/udp
    stdin_open: true
    tty: true
```
then from the commandline inside that folder do
`docker-compose up` then `docker logs bds -f` and wait until you see server started, once that happens press ctrl c, then a folder named data should appear inside bds folder, inside that folder edit server.properties, then do `docker-compose down` inside bds, and start again with `docker-compose up -d`.

once the server is running to make yourself op, `docker attach bds` type list enter to test it is working, then op GAMERTAG enter. to dettach do ctrl p q, dont ctrl c cuz it kills the server
