### ISSUE TITLE
SERVER_PORT environment variable - add to documentation

### ISSUE THREAD

**Issue by LunkSnee** [itzg/docker-minecraft-bedrock-server#77]
I tried to have two game servers hosted using this on the same system.
I was running into trouble with the ports conflicting, until I found the "SERVER_PORT" environment variable.

I suggest including that in the list of usable environment variables. The normal port mapping for docker (outside port 19111->19132, for example) didn't seem to work for me. Including the alternative port with the SERVER_PORT environment variable solved the problem and made the servers available.

**Comment by itzg** [comment]
There is indeed something strange with Bedrock's port handling, but before getting into that, `SERVER_PORT` is listed in the README:

![image](https://user-images.githubusercontent.com/988985/86402598-b7d90180-bc71-11ea-91c2-c62797a141fa.png)

Was there something else you meant by "I suggest including that in the list of usable environment variables."?

Now what's strange, is that this same compose file worked on an Ubuntu 20.04 system:

```yaml
version: "3.8"

services:
  mc132:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      SERVER_NAME: Server132
    ports:
    - 19132:19132/udp
  mc133:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      SERVER_NAME: Server133
    ports:
    - 19133:19132/udp
  mc134:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      SERVER_NAME: Server134
    ports:
      - 19134:19132/udp
```

however, it didn't work on Docker Desktop running on Windows (WSL2). 

Here's the docker version info for the system that did work:
```
Server:
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.12
  Git commit:       77e06fd
  Built:            Mon Jun  8 20:24:59 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

On Docker Desktop I even tried adding `SERVER_PORT` and adjusting the port mappings accordingly, but that didn't work for me either.
