### ISSUE TITLE
"You need to authenticate to Microsoft Services"

### ISSUE THREAD

**Issue by ryaniskira** [itzg/docker-minecraft-bedrock-server#90]
No matter what I do, I can't seem to get around this issue.

- My system time is correct (To make 100% sure the time is correct I linked `/etc/localtime` from the host)
- My internet connection is working 100% without issues
- I am signed in on the client
- I even tried the fix mentioned in #29 regarding forwarding both TCP and UDP ports, along with a custom resolv.conf (pointing to Cloudflare) just in case my adblocking DNS was the issue. Here is the relevant snippet from my docker-compose:

```
# Minecraft Bedrock Server
    minecraft-bedrock-server:
        container_name: Minecraft-Bedrock
        environment:
            - EULA=TRUE
            - 'SERVER_NAME=Freyja Bedrock Server'
            - ALLOW_CHEATS=false
            - DEFAULT_PLAYER_PERMISSION_LEVEL=visitor
            - ONLINE_MODE=true
            - MAX_THREADS=8
            - GAMEMODE=survival
            - DIFFICULTY=easy
            - VIEW_DISTANCE=32
            - TICK_DISTANCE=4
        volumes:
            - '/mnt/Media/Sandbox/Minecraft-Bedrock/data:/data'
            - '/mnt/Media/Sandbox/Minecraft-Bedrock/resolv.conf:/etc/resolv.conf'
            - '/etc/localtime:/etc/localtime:ro'
        ports:
            - '19132:19132/udp'
            - '19132:19132'
        image: itzg/minecraft-bedrock-server
        stdin_open: true
        tty: true
```
